version: "3.8"

services:
  movies_admin:
    build:
      context: ../movies_admin/
      dockerfile: ../docker_compose/Dockerfile
      args:
        BUILD_MODE: dev
    command: make run-dev-server-docker
    env_file:
      - ./.envs/.dev/.django
      - ./.envs/.dev/.db
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:13.0-alpine
    env_file:
      - ./.envs/.dev/.db
    restart: unless-stopped
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      # Create db schema on container first launch
      - ./utils/create_postgres_schema:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

volumes:
  postgres_volume:
